workflows:
  ios_simulator:
    name: iOS Simulator (.app)
    environment:
      flutter: "3.7.2"   # Dart 3 içerir
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Show versions
        script: |
          flutter --version
          dart --version
      - name: Flutter deps
        script: flutter pub get
      - name: CocoaPods
        script: |
          cd ios
          pod repo update
          pod install
          cd ..
      - name: Build for iOS Simulator (no signing)
        script: flutter build ios --simulator --release
      - name: Zip Runner.app for download
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner-sim.zip Runner.app
    artifacts:
      - build/ios/iphonesimulator/Runner-sim.zip
