workflows:
  ios_simulator:
    name: iOS Simulator (.app)
    environment:
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Force Flutter 3.35.3 + build
        script: |
          set -e
          echo ">>> Installing Flutter 3.35.3"
          git clone https://github.com/flutter/flutter.git -b 3.35.3 $HOME/flutter_3_35_3
          export PATH="$HOME/flutter_3_35_3/bin:$PATH"
          flutter --version
          dart --version

          echo ">>> flutter pub get"
          flutter pub get

          echo ">>> CocoaPods"
          cd ios
          pod repo update
          pod install
          cd ..

          echo ">>> Build iOS Simulator"
          flutter build ios --simulator --release

          echo ">>> Zip app"
          cd build/ios/iphonesimulator
          zip -r Runner-sim.zip Runner.app
    artifacts:
      - build/ios/iphonesimulator/Runner-sim.zip
