# codemagic.yaml — iOS Simulator build (no codesign)
workflows:
  ios_simulator:
    name: iOS Simulator Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: 3.35.3
      xcode: 16.1
      cocoapods: 1.15.2
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - $HOME/Library/Developer/Xcode/DerivedData
        - $HOME/Library/Caches/CocoaPods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Flutter & Pods
        script: |
          flutter --version
          flutter pub get
          cd ios
          pod repo update
          pod install
          cd ..
      - name: Build iOS (Simulator, no codesign)
        script: |
          # Debug simülator derlemesi (en hızlı seçenek).
          flutter build ios --simulator --debug --no-codesign
          # İstersen release simülator: flutter build ios --simulator --release --no-codesign
      - name: Paketle (.app → .zip)
        script: |
          APP_DIR="build/ios/iphonesimulator"
          APP_PATH=$(find "$APP_DIR" -maxdepth 1 -name "*.app" | head -n1)
          if [ -z "$APP_PATH" ]; then
            echo "Simulator .app bulunamadı"; exit 1
          fi
          echo "APP_PATH=$APP_PATH"
          cd "$APP_DIR"
          zip -r "Runner.app.zip" "$(basename "$APP_PATH")"
          echo "Ziplendi: $APP_DIR/Runner.app.zip"
    artifacts:
      - build/ios/iphonesimulator/*.app
      - build/ios/iphonesimulator/Runner.app.zip
      - flutter_drive.log
