workflows:
  ios_simulator:
    name: iOS Simulator Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: 3.35.3
      xcode: 16.1
      cocoapods: 1.16.2
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - $HOME/Library/Developer/Xcode/DerivedData
        - $HOME/Library/Caches/CocoaPods
    triggering:
      events: [ push ]
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: CocoaPods yükselt (gerekirse) ve hazırlık
        script: |
          pod --version || true
          # Bazı imajlarda brew/gem çakışması olabiliyor; aşağıdaki satırlar güvenli:
          sudo gem install cocoapods -v '>=1.16.2'
          pod repo update
      - name: Flutter & Pods temiz kurulum
        script: |
          flutter --version
          flutter clean
          flutter pub get
          rm -rf ios/Pods ios/Podfile.lock
          cd ios
          pod deintegrate || true
          pod install
          cd ..
      - name: iOS (Simulator, no codesign) build
        script: |
          # En hızlı: Debug sim
          flutter build ios --simulator --debug --no-codesign
          # İstersen release sim:
          # flutter build ios --simulator --release --no-codesign
      - name: .app paketle (zip)
        script: |
          APP_DIR="build/ios/iphonesimulator"
          APP_PATH=$(find "$APP_DIR" -maxdepth 1 -name "*.app" | head -n1)
          if [ -z "$APP_PATH" ]; then
            echo "Simulator .app bulunamadı"; exit 1
          fi
          cd "$APP_DIR"
          zip -r "Runner.app.zip" "$(basename "$APP_PATH")"
          echo "Ziplendi: $APP_DIR/Runner.app.zip"
    artifacts:
      - build/ios/iphonesimulator/*.app
      - build/ios/iphonesimulator/Runner.app.zip
      - flutter_drive.log
