workflows:
  ios_simulator:
    name: iOS Simulator Build (Flutter.h fix)
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: 3.35.3
      xcode: 16.1
      cocoapods: 1.16.2
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - $HOME/Library/Developer/Xcode/DerivedData
        - $HOME/Library/Caches/CocoaPods
    scripts:
      - name: Flutter hazırlık
        script: |
          set -euxo pipefail
          flutter --version
          flutter precache --ios --force
          flutter pub get
      - name: Pods temizliği
        script: |
          set -euxo pipefail
          rm -rf ios/Pods ios/Podfile.lock
          cd ios
          pod repo update
          pod deintegrate || true
          cd ..
      - name: Pod install
        script: |
          set -euxo pipefail
          cd ios
          pod install --verbose
          cd ..
      - name: iOS (Simulator, no codesign) build
        script: |
          set -euxo pipefail
          # En hızlı: Debug sim
          flutter clean
          flutter build ios --simulator --debug --no-codesign
      - name: .app paketle (zip)
        script: |
          set -euxo pipefail
          APP_DIR="build/ios/iphonesimulator"
          APP_PATH=$(find "$APP_DIR" -maxdepth 1 -name "*.app" | head -n1)
          if [ -z "$APP_PATH" ]; then
            echo "Simulator .app bulunamadı"; exit 1
          fi
          cd "$APP_DIR"
          zip -r "Runner.app.zip" "$(basename "$APP_PATH")"
          echo "Ziplendi: $APP_DIR/Runner.app.zip"
    artifacts:
      - build/ios/iphonesimulator/*.app
      - build/ios/iphonesimulator/Runner.app.zip
      - flutter_drive.log
