workflows:
  ios_simulator:
    name: iOS Simulator (.app)
    environment:
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Build with Flutter 3.35.3 (Dart 3.5)
        script: |
          set -e
          FVER=3.35.3
          echo ">>> Install Flutter $FVER"
          git clone --depth 1 -b $FVER https://github.com/flutter/flutter.git $HOME/flutter_$FVER
          export PATH="$HOME/flutter_$FVER/bin:$PATH"
          flutter --version
          dart --version

          echo ">>> flutter pub get"
          flutter pub get

          echo ">>> CocoaPods"
          cd ios
          pod repo update
          pod install
          cd ..

          echo ">>> Build iOS Simulator"
          flutter build ios --simulator --release

          echo ">>> Zip app"
          cd build/ios/iphonesimulator
          zip -r Runner-sim.zip Runner.app
    artifacts:
      - build/ios/iphonesimulator/Runner-sim.zip
