name: hizlipazaresnaf
description: "Hızlı Pazar Esnaf Uygulaması"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^0.13.6
  file_picker: ^10.2.0
  image_picker: ^1.0.5
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  flutter_svg: ^2.0.7
  webview_flutter: ^4.7.0
  intl: ^0.20.2
  cached_network_image: ^3.3.0
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bg.png
    - assets/logo.svg
    - assets/icon.png
    - web/payment_result.html
    
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png" # YOLUNU DÜZENLE
