# ios/Podfile
platform :ios, '13.0'

use_frameworks! :linkage => :static
use_modular_headers!

flutter_root = ENV['FLUTTER_ROOT']
unless flutter_root && File.exist?(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'))
  # Codemagic'de FLUTTER_ROOT genelde set olur. Olmazsa "which flutter" ile türetelim.
  which_flutter = `which flutter`.strip
  if which_flutter != '' && File.exist?(which_flutter)
    flutter_root = File.expand_path('../../', File.dirname(which_flutter)) # .../bin/flutter -> sdk kökü
  end
end

raise "FLUTTER_ROOT could not be determined" unless flutter_root

require File.expand_path('packages/flutter_tools/bin/podhelper', flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
